name: Sync Kobo to Baserow

on:
  schedule:
    - cron: "*/30 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run sync
        run: node sync.js
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
          BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}

      - name: Commit state
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add last_id.txt
          git commit -m "update last_id" || echo "no changes"
          git push
